### ISSUE TITLE
Question: should we rename this repo?

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/geocml-base-image#10]
I'm in favor or renaming the repository to geocml-base-image, or something similar. Yes we use Kasm for our base image, but I think it would be a good idea to develop our own branding as we continue to develop this project. 

I wanted to open this issue to start a thread of conversation about this. What do you think we should do?

**Comment by capsulecorplab** [comment]
Open to a more on-brand name. geocml-base-image implies there could be other images built on top of this one; what would the naming convention be for such images built on top of the base image?

As far as other name ideas, I kind of like geocml-desktop

**Comment by TristanDamron** [comment]
I'm in favor of geocml-base-image since this repo will hold the minimum required image for a geoCML deployment. Users may, and are encouraged to, fork the base image and customize it to their specific use case. 

I think that geocml-desktop would be a bit misleading. Remember that geoCML is a multiparadigm GIS; calling it geocml-desktop implies that you cannot use geoCML as a server application running in the cloud. I also think that there will be some users who want to use their geoCML system headless (choosing not to use Kasm VNC).

**Comment by TristanDamron** [comment]
@capsulecorplab Keeping this warm; how do you feel about geocml-base-image?

**Comment by capsulecorplab** [comment]
> @capsulecorplab Keeping this warm; how do you feel about geocml-base-image?

SGTM :slightly_smiling_face:

**Comment by TristanDamron** [comment]
Done! :tada:

**Comment by capsulecorplab** [comment]
should also update the image name in https://github.com/geoCML/geocml-base-image/blob/main/docker-compose.yml#L6

**Comment by TristanDamron** [comment]
Whoopsies! Fixed with [5deec6c](https://github.com/geoCML/geocml-base-image/commit/5deec6c79aec2c8bf7c02852b2062037ef0ecd5c)
