### ISSUE TITLE
Unnecessary install of markupsafe in Dockerfile

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/geocml-base-image#27]
There is a redundant line to install markupsafe=2.0.1 in the Dockerfile. This was introduced previously since our QGIS install did not install markupsafe as a dependency. With #14, this module is installed with QGIS meaning we can remove that second (useless) installation line from the Dockerfile.

**Comment by Ahmad-Mukhtar** [comment]
I'll work on this.

**Comment by TristanDamron** [comment]
Resolved with #28
