### ISSUE TITLE
Back up Postgres data when container stops

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/geocml-base-image#8]
As of PR #6, any data created in geocml_db while the container was running is deleted when the container stops. We should ensure that when a geoCML container stops that the Postgres database within the container is backed up to a permanent storage location. Further, when a container is started we should check for any backups that maybe present on the host device and restore the geocml_db database once the container goes back up.

**Comment by capsulecorplab** [comment]
Where is the geocml_db saved in the file system inside the kasm session? If it's saved in `/home/kasm-user`, the data should persist

**Comment by capsulecorplab** [comment]
Could `/var/lib/postgresql/12/main` just be a symlink to a path on the persistence layer?

**Comment by TristanDamron** [comment]
Unfortunately not, since /var/ gets wiped when the container goes down.

**Comment by TristanDamron** [comment]
It's not hard to change the default data directory to point to a directory in the persistence layer, just comes with the draw back of using extra space on the host's filesystem. For medium-to-large datasets (>10GB), I could see that becoming an issue. Whereas with a database dump to a single file, we don't run into that problem.
